/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.glaforge.gemini.interactions;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

/**
 * Represents the stateful sandbox workspace of a Managed Agent environment.
 * <p>
 * This class caches the downloaded files of the sandbox in a temporary local
 * file, letting developers inspect, search, and read files generated by the
 * remote agent without repeatedly invoking network requests.
 * Individual file content is loaded lazily on demand.
 * </p>
 * <p>
 * Use {@link #refresh()} to pull the latest environment state, and
 * {@link #close()} to clean up the temporary files.
 * </p>
 */
public class AgentEnvironment implements AutoCloseable {

    private final String interactionId;
    private final GeminiInteractionsClient client;
    private Path tempTarPath;
    private Map<String, TarParser.TarEntryMetadata> index = new HashMap<>();

    AgentEnvironment(String interactionId, GeminiInteractionsClient client) {
        this.interactionId = interactionId;
        this.client = client;
    }

    /**
     * Gets the interaction ID associated with this environment.
     *
     * @return The interaction ID.
     */
    public String getInteractionId() {
        return interactionId;
    }

    /**
     * Refreshes the environment files by downloading the latest snapshot from the
     * API.
     *
     * @return this instance for method chaining.
     * @throws GeminiInteractionsException if the download or parsing fails.
     */
    public synchronized AgentEnvironment refresh() {
        cleanupTempFile();

        try {
            tempTarPath = Files.createTempFile("gemini-env-" + interactionId + "-", ".tar");
            try (InputStream in = client.downloadEnvironment(interactionId)) {
                Files.copy(in, tempTarPath, StandardCopyOption.REPLACE_EXISTING);
            }
            System.out.println("Downloaded TAR size: " + Files.size(tempTarPath) + " bytes");
            Map<String, TarParser.TarEntryMetadata> rawIndex = TarParser.scanTar(tempTarPath);
            this.index = new HashMap<>();
            for (Map.Entry<String, TarParser.TarEntryMetadata> entry : rawIndex.entrySet()) {
                this.index.put(normalizePath(entry.getKey()), entry.getValue());
            }
        } catch (IOException e) {
            cleanupTempFile();
            throw new GeminiInteractionsException("Failed to refresh environment files", e);
        }
        return this;
    }

    /**
     * Lists the relative paths of all regular files present in the environment
     * workspace.
     *
     * @return A set of relative file paths.
     */
    public Set<String> listFiles() {
        return Collections.unmodifiableSet(index.keySet());
    }

    /**
     * Checks if a file exists in the environment workspace.
     *
     * @param path The relative path of the file.
     * @return true if the file exists, false otherwise.
     */
    public boolean fileExists(String path) {
        return index.containsKey(normalizePath(path));
    }

    /**
     * Lazily reads a file's contents from the cached TAR archive.
     *
     * @param path The relative path of the file in the environment.
     * @return A byte array containing the file contents, or an empty byte array if
     *         the file is not found or empty.
     */
    public byte[] readBinaryFile(String path) {
        if (tempTarPath == null) {
            return new byte[0];
        }
        TarParser.TarEntryMetadata meta = index.get(normalizePath(path));
        if (meta == null) {
            return new byte[0];
        }
        try (InputStream in = Files.newInputStream(tempTarPath)) {
            long skipped = in.skip(meta.offset());
            while (skipped < meta.offset()) {
                long s = in.skip(meta.offset() - skipped);
                if (s <= 0) {
                    break;
                }
                skipped += s;
            }
            byte[] bytes = new byte[(int) meta.size()];
            int total = 0;
            while (total < bytes.length) {
                int count = in.read(bytes, total, bytes.length - total);
                if (count < 0) {
                    break;
                }
                total += count;
            }
            if (total < bytes.length) {
                return new byte[0];
            }
            return bytes;
        } catch (IOException e) {
            throw new GeminiInteractionsException("Failed to read file from environment archive", e);
        }
    }

    /**
     * Lazily reads a file's contents as a UTF-8 string from the cached TAR archive.
     *
     * @param path The relative path of the file in the environment.
     * @return The text content of the file, or an empty string if the file is not
     *         found or empty.
     */
    public String readTextFile(String path) {
        byte[] bytes = readBinaryFile(path);
        if (bytes.length == 0) {
            return "";
        }
        return new String(bytes, StandardCharsets.UTF_8);
    }

    /**
     * Extracts and copies a specific file from the environment to a local file
     * path.
     *
     * @param path            The relative path of the file in the environment.
     * @param targetLocalPath The local target file path.
     * @throws IOException            If writing to the target path fails.
     * @throws NoSuchElementException If the file does not exist in the environment.
     */
    public void downloadFile(String path, Path targetLocalPath) throws IOException {
        if (tempTarPath == null) {
            throw new NoSuchElementException("Environment workspace is empty or has not been refreshed.");
        }
        TarParser.TarEntryMetadata meta = index.get(normalizePath(path));
        if (meta == null) {
            throw new NoSuchElementException("File '" + path + "' does not exist in this environment workspace.");
        }
        if (targetLocalPath.getParent() != null) {
            Files.createDirectories(targetLocalPath.getParent());
        }
        try (InputStream in = Files.newInputStream(tempTarPath);
                OutputStream out = Files.newOutputStream(targetLocalPath)) {
            long skipped = in.skip(meta.offset());
            while (skipped < meta.offset()) {
                long s = in.skip(meta.offset() - skipped);
                if (s <= 0) {
                    break;
                }
                skipped += s;
            }
            byte[] buffer = new byte[8192];
            long remaining = meta.size();
            while (remaining > 0) {
                int toRead = (int) Math.min(buffer.length, remaining);
                int count = in.read(buffer, 0, toRead);
                if (count < 0) {
                    break;
                }
                out.write(buffer, 0, count);
                remaining -= count;
            }
        }
    }

    @Override
    public synchronized void close() {
        cleanupTempFile();
    }

    private void cleanupTempFile() {
        if (tempTarPath != null) {
            try {
                Files.deleteIfExists(tempTarPath);
            } catch (IOException e) {
                // Ignore failure to delete temp file
            } finally {
                tempTarPath = null;
                index.clear();
            }
        }
    }

    private String normalizePath(String path) {
        if (path == null) {
            return "";
        }
        if (path.startsWith("./")) {
            path = path.substring(2);
        }
        if (path.startsWith("/")) {
            path = path.substring(1);
        }
        return path;
    }
}
