/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.glaforge.gemini.interactions.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.time.Instant;

/**
 * Represents the Interaction resource.
 *
 * @param id                    The unique identifier for the interaction.
 * @param model                 The model used for the interaction.
 * @param agent                 The agent used for the interaction.
 * @param created               Creation timestamp.
 * @param updated               Last update timestamp.
 * @param status                The status of the interaction.
 * @param steps                 List of steps.
 * @param usage                 Token usage details.
 * @param previousInteractionId ID of the previous interaction in the conversation.
 * @param environmentId         ID of the environment.
 * @param cachedContent         URI of the cached content used.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record Interaction(
    String id,
    String model,
    String agent,
    Instant created,
    Instant updated,
    Status status,
    List<Step> steps,
    Usage usage,
    @JsonProperty("previous_interaction_id") String previousInteractionId,
    @JsonProperty("environment_id") String environmentId,
    @JsonProperty("cached_content") String cachedContent
) {

    /**
     * Extracts the concatenated text from the last consecutive model output steps.
     *
     * @return The output text, or null if not found.
     */
    public String outputText() {
        if (steps == null || steps.isEmpty()) {
            return null;
        }

        StringBuilder textBuilder = new StringBuilder();
        boolean done = false;

        for (int i = steps.size() - 1; i >= 0; i--) {
            Step step = steps.get(i);
            if (done) break;

            if (step instanceof Step.ModelOutputStep modelOutputStep) {
                if (modelOutputStep.content() != null) {
                    for (int j = modelOutputStep.content().size() - 1; j >= 0; j--) {
                        Content content = modelOutputStep.content().get(j);
                        if (content instanceof Content.TextContent textContent) {
                            textBuilder.insert(0, textContent.text());
                        } else {
                            done = true;
                            break;
                        }
                    }
                }
            } else {
                break;
            }
        }

        String result = textBuilder.toString();
        return result.isEmpty() ? null : result;
    }

    /**
     * Extracts the last image generated by the model in response to the current request.
     *
     * @return The image content, or null if not found.
     */
    public Content.ImageContent outputImage() {
        if (steps == null || steps.isEmpty()) return null;
        for (int i = steps.size() - 1; i >= 0; i--) {
            Step step = steps.get(i);
            if (step instanceof Step.UserInputStep) break;
            if (step instanceof Step.ModelOutputStep modelOutputStep && modelOutputStep.content() != null) {
                for (int j = modelOutputStep.content().size() - 1; j >= 0; j--) {
                    Content content = modelOutputStep.content().get(j);
                    if (content instanceof Content.ImageContent imageContent) {
                        return imageContent;
                    }
                }
            }
        }
        return null;
    }

    /**
     * Extracts the last audio generated by the model in response to the current request.
     *
     * @return The audio content, or null if not found.
     */
    public Content.AudioContent outputAudio() {
        if (steps == null || steps.isEmpty()) return null;
        for (int i = steps.size() - 1; i >= 0; i--) {
            Step step = steps.get(i);
            if (step instanceof Step.UserInputStep) break;
            if (step instanceof Step.ModelOutputStep modelOutputStep && modelOutputStep.content() != null) {
                for (int j = modelOutputStep.content().size() - 1; j >= 0; j--) {
                    Content content = modelOutputStep.content().get(j);
                    if (content instanceof Content.AudioContent audioContent) {
                        return audioContent;
                    }
                }
            }
        }
        return null;
    }

    /**
     * Extracts the last video generated by the model in response to the current request.
     *
     * @return The video content, or null if not found.
     */
    public Content.VideoContent outputVideo() {
        if (steps == null || steps.isEmpty()) return null;
        for (int i = steps.size() - 1; i >= 0; i--) {
            Step step = steps.get(i);
            if (step instanceof Step.UserInputStep) break;
            if (step instanceof Step.ModelOutputStep modelOutputStep && modelOutputStep.content() != null) {
                for (int j = modelOutputStep.content().size() - 1; j >= 0; j--) {
                    Content content = modelOutputStep.content().get(j);
                    if (content instanceof Content.VideoContent videoContent) {
                        return videoContent;
                    }
                }
            }
        }
        return null;
    }

    /**
     * Represents a single turn in an interaction.
     *
     * @param role    The role of the participant.
     * @param content The content of the turn (String or List&lt;Content&gt;).
     */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public record Turn(
        Role role,
        Object content // String or List<Content>
    ) {}

    /**
     * Token usage details.
     *
     * @param totalInputTokens        Total input tokens.
     * @param inputTokensByModality   Input tokens broken down by modality.
     * @param totalCachedTokens       Total cached tokens.
     * @param cachedTokensByModality  Cached tokens broken down by modality.
     * @param totalOutputTokens       Total output tokens.
     * @param outputTokensByModality  Output tokens broken down by modality.
     * @param totalToolUseTokens      Total tool use tokens.
     * @param toolUseTokensByModality Tool use tokens broken down by modality.
     * @param totalThoughtTokens      Total thought (reasoning) tokens.
     * @param totalTokens             Total tokens.
     */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public record Usage(
        @JsonProperty("total_input_tokens") Integer totalInputTokens,
        @JsonProperty("input_tokens_by_modality") List<ModalityTokens> inputTokensByModality,
        @JsonProperty("total_cached_tokens") Integer totalCachedTokens,
        @JsonProperty("cached_tokens_by_modality") List<ModalityTokens> cachedTokensByModality,
        @JsonProperty("total_output_tokens") Integer totalOutputTokens,
        @JsonProperty("output_tokens_by_modality") List<ModalityTokens> outputTokensByModality,
        @JsonProperty("total_tool_use_tokens") Integer totalToolUseTokens,
        @JsonProperty("tool_use_tokens_by_modality") List<ModalityTokens> toolUseTokensByModality,
        @JsonProperty("total_thought_tokens") Integer totalThoughtTokens,
        @JsonProperty("total_tokens") Integer totalTokens,
        @JsonProperty("grounding_tool_count") List<GroundingToolCount> groundingToolCount
    ) {}

    /**
     * Tokens broken down by modality.
     *
     * @param modality The modality.
     * @param tokens   The number of tokens.
     */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public record ModalityTokens(
        Modality modality,
        Integer tokens
    ) {}

    /**
     * Grounding tool count.
     *
     * @param count The number of grounding tool counts.
     * @param type  The grounding tool type associated with the count.
     */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public record GroundingToolCount(
        Integer count,
        String type
    ) {}

    /**
     * Interaction modalities.
     */
    public enum Modality {
        /** Text modality. */
        @JsonProperty("text") TEXT,
        /** Image modality. */
        @JsonProperty("image") IMAGE,
        /** Audio modality. */
        @JsonProperty("audio") AUDIO,
        /** Video modality. */
        @JsonProperty("video") VIDEO
    }

    /**
     * Interaction status.
     */
    public enum Status {
        /** Interaction in progress. */
        @JsonProperty("in_progress") IN_PROGRESS,
        /** Interaction requires usage action. */
        @JsonProperty("requires_action") REQUIRES_ACTION,
        /** Interaction completed successfully. */
        @JsonProperty("completed") COMPLETED,
        /** Interaction failed. */
        @JsonProperty("failed") FAILED,
        /** Interaction cancelled. */
        @JsonProperty("cancelled") CANCELLED;
        
        /**
         * Checks whether the status represents a finished state.
         *
         * @return true if the status is COMPLETED, FAILED, or CANCELLED.
         */
        public boolean isFinished() {
            return this == COMPLETED || this == FAILED || this == CANCELLED;
        }
    }

    /**
     * Interaction participant role.
     */
    public enum Role {
        /** User role. */
        @JsonProperty("user") USER,
        /** Model role. */
        @JsonProperty("model") MODEL,
        /** Agent role. */
        @JsonProperty("agent") AGENT
    }
}
